string name, address, phone;
Console.WriteLine("Moi ban nhap ten: ");
name = Console.ReadLine();
Console.WriteLine("Moi ban nhap dia chi: ");
address = Console.ReadLine();
Console.WriteLine("Moi ban nhap phone: ");
phone = Console.ReadLine();
Console.WriteLine("Thong tin:");
Console.WriteLine($"Name : {name}");
Console.WriteLine($"Adress: {address}");
Console.WriteLine($"Phone: {phone}");